# Generated by Django 3.2.3 on 2021-05-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilidator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(verbose_name='twitter URL'),
        ),
    ]
