# https://developers.google.com/maps/documentation/places/web-service/supported_types


TYPE_CHOICES = [
    ('', 'All types'),
    ('accounting', 'Accounting'),
    ('airport', 'Airport'),
    ('amusement_park', 'Amusement park'),
    ('aquarium', 'Aquarium'),
    ('art_gallery', 'Art gallery'),
    ('atm', 'ATM'),
    ('bakery', 'Bakery'),
    ('bank', 'Bank'),
    ('bar', 'Bar'),
    ('beauty_salon', 'Beauty salon'),
    ('bicycle_store', 'Bicycle store'),
    ('book_store', 'Book store'),
    ('bowling_alley', 'Bowling alley'),
    ('bus_station', 'Bus station'),
    ('cafe', 'Cafe'),
    ('campground', 'Campground'),
    ('car_dealer', 'Car dealer'),
    ('car_rental', 'Car rental'),
    ('car_repair', 'Car repair'),
    ('car_wash', 'Car wash'),
    ('casino', 'Casino'),
    ('cemetery', 'Cemetery'),
    ('church', 'Church'),
    ('city_hall', 'City hall'),
    ('clothing_store', 'Clothing store'),
    ('convenience_store', 'Convenience store'),
    ('courthouse', 'Courthouse'),
    ('dentist', 'Dentist'),
    ('department_store', 'Department store'),
    ('doctor', 'Doctor'),
    ('drugstore', 'Drugstore'),
    ('electrician', 'Electrician'),
    ('electronics_store', 'Electronics store'),
    ('embassy', 'Embassy'),
    ('fire_station', 'Fire station'),
    ('florist', 'Florist'),
    ('funeral_home', 'Funeral home'),
    ('furniture_store', 'Furniture store'),
    ('gas_station', 'Gas station'),
    ('gym', 'Gym'),
    ('hair_care', 'Hair care'),
    ('hardware_store', 'Hardware store'),
    ('hindu_temple', 'Hindu temple'),
    ('home_goods_store', 'Home goods store'),
    ('hospital', 'Hospital'),
    ('insurance_agency', 'Insurance agency'),
    ('jewelry_store', 'Jewelry store'),
    ('laundry', 'Laundry'),
    ('lawyer', 'Lawyer'),
    ('library', 'Library'),
    ('light_rail_station', 'Light rail station'),
    ('liquor_store', 'Liquor store'),
    ('local_government_office', 'Local government office'),
    ('locksmith', 'Locksmith'),
    ('lodging', 'Lodging'),
    ('meal_delivery', 'Meal delivery'),
    ('meal_takeaway', 'Meal takeaway'),
    ('mosque', 'Mosque'),
    ('movie_rental', 'Movie rental'),
    ('movie_theater', 'Movie theater'),
    ('moving_company', 'Moving company'),
    ('museum', 'Museum'),
    ('night_club', 'Night club'),
    ('painter', 'Painter'),
    ('park', 'Park'),
    ('parking', 'Parking'),
    ('pet_store', 'Pet store'),
    ('pharmacy', 'Pharmacy'),
    ('physiotherapist', 'Physiotherapist'),
    ('plumber', 'Plumber'),
    ('police', 'Police'),
    ('post_office', 'Post office'),
    ('primary_school', 'Primary school'),
    ('real_estate_agency', 'Real estate agency'),
    ('restaurant', 'Restaurant'),
    ('roofing_contractor', 'Roofing contractor'),
    ('rv_park', 'RV park'),
    ('school', 'School'),
    ('secondary_school', 'Secondary school'),
    ('shoe_store', 'Shoe store'),
    ('shopping_mall', 'Shopping mall'),
    ('spa', 'Spa'),
    ('stadium', 'Stadium'),
    ('storage', 'Storage'),
    ('store', 'Store'),
    ('subway_station', 'Subway station'),
    ('supermarket', 'Supermarket'),
    ('synagogue', 'Synagogue'),
    ('taxi_stand', 'Taxi stand'),
    ('tourist_attraction', 'Tourist attraction'),
    ('train_station', 'Train station'),
    ('transit_station', 'Transit station'),
    ('travel_agency', 'Travel agency'),
    ('university', 'University'),
    ('veterinary_care', 'Veterinary care'),
    ('zoo', 'Zoo'),
]