import random


chapters = [
    'Absolvers',
    'Accipiters',
    'Adamantine Lions',
    'Adulators',
    'Angel Guard',
    'Angels Encarmine',
    'Angels Eradicant',
    'Angels Excelsis',
    'Angels Glorious',
    'Angels Numinous',
    'Angels of Absolution',
    'Angels of Damnation',
    'Angels of Defiance',
    'Angels of Fire',
    'Angels of Fury',
    'Angels of Iron',
    'Angels of Light',
    'Angels of Penance',
    'Angels of Purgatory',
    'Angels of Redemption',
    'Angels of Repentance',
    'Angels of Retribution',
    'Angels of Vengeance',
    'Angels of Vigilance',
    'Angels of Wrath',
    'Angels Penitent',
    'Angels Porphyr',
    'Angels Puissant',
    'Angels Redeemed',
    'Angels Repentant',
    'Angels Resplendent',
    'Angels Revenant',
    'Angels Sanguine',
    'Angels Vermillion',
    'Angels Vindicant',
    'Astral Bears',
    'Astral Drakes',
    'Astral Fists',
    'Astral Hawks',
    'Astral Knights',
    'Atlantian Spears',
    'Auric Patricians',
    'Aurora Chapter',
    'Aurora Talons',
    'Avengers',
    'Avenging Sons',
    'Benedictors',
    'Black Consuls',
    'Black Crusaders',
    'Black Dragons',
    'Black Guard',
    'Black Inculpators',
    'Black Ravens',
    'Black Talons',
    'Black Templars',
    'Black Vipers',
    'Black Vultures',
    'Black Wings',
    'Blazoned Legion',
    'Blades of Vengeance',
    'Blood Angels',
    'Blood Dragons',
    'Blood Drinkers',
    'Blood Knights',
    'Blood Eagles',
    'Blood Legion',
    'Blood Ravens',
    'Blood Scythes',
    'Blood Swords',
    'Blood Tigers',
    'Blood Wings',
    'Bone Knives',
    'Brazen Consuls',
    'Brazen Claws',
    'Brazen Fists',
    'Brazen Minotaurs',
    'Brazen Skulls',
    'Brothers of Jarad',
    'Brotherhood of a Thousand',
    'Brothers of the Red',
    'Brothers Penitent',
    'Burning Blood',
    'Carcharodons',
    'Carmine Blades',
    'Castellans of the Rift',
    'Celebrants',
    'Celestial Guard',
    'Celestial Lions',
    'Celestial Swords',
    'Celestian Guard',
    'Cerulean Guard',
    'Champions of Thanatos',
    'Charnel Guard',
    'Chorus of Eltain',
    'Clerics of Steel',
    'Consecrators',
    'Contenders',
    'Covenant of Fire',
    'Crimson Castellans',
    'Crimson Consuls',
    'Crimson Fists',
    'Crimson Guard',
    'Crimson Legion',
    'Crimson Paladins',
    'Crimson Sabres',
    'Crimson Scions',
    'Crimson Scythes',
    'Crimson Shades',
    'Crimson Swords',
    'Crimson Talons',
    'Crimson Templars',
    'Cruor Blades',
    'Crusaders',
    'Crusaders of Dorn',
    'Dark Angels',
    'Dark Brotherhood',
    'Dark Crusaders',
    'Dark Eagles',
    'Dark Hands',
    'Dark Hunters',
    'Dark Krakens',
    'Dark Paladins',
    'Dark Sons',
    'Dark Swords',
    'Dark Templars',
    'Darkspires',
    'Death Eagles',
    'Death Hawks',
    'Death Knights',
    'Death Spectres',
    'Death Strike',
    'Deathwatch',
    'Desert Lions',
    'Destroyers',
    'Dictators',
    'Disciples of Blood',
    'Disciples of Caliban',
    'Doom Eagles',
    'Doom Griffons',
    'Doom Legion',
    'Doom Warriors',
    'Doomsayers',
    'Dragonspears',
    'Dragon Lords',
    'Eagle Warriors',
    'Ebon Knights',
    "Emperor's Claws",
    "Emperor's Hands",
    "Emperor's Hawks",
    "Emperor's Scythes",
    "Emperor's Shadows",
    "Emperor's Shields",
    "Emperor's Spears",
    "Emperor's Storm",
    "Emperor's Swords",
    "Emperor's Swords (Bellicas)",
    "Emperor's Warbringers",
    "Emperor's Wolves",
    "Emperor's Wrath",
    'Espandors',
    'Excoriators',
    'Excubants',
    'Execrators',
    'Executioners',
    'Exemplars',
    'Exorcists',
    'Exsanguinators',
    'Falling Star',
    'Fire Angels',
    'Fire Claws',
    'Fire Hawks',
    'Fire Lords',
    'Fists Exemplar',
    'Flame Eagles',
    'Flame Falcons',
    'Flesh Eaters',
    'Flesh Tearers',
    'Fulminators',
    'Genesis Chapter',
    'Golden Blades',
    'Golden Gryphons',
    'Golden Halos',
    'Golden Paladins',
    'Golden Sons',
    'Gore Golems',
    'Gorgons',
    'Graven Fists',
    'Graven Spectres',
    'Grey Knights',
    'Grey Slayers',
    'Grief Bringers',
    'Griffon Lords',
    'Guardians of Celeres',
    'Guardians of the Covenant',
    'Halo Brethren',
    'Halo Dragons',
    'Hammers of Dorn',
    'Hammers of Retribution',
    'Harbingers',
    'Hawk Lords',
    'Helion Legion',
    'Heralds of Ultramar',
    'Heralds of Vengeance',
    'Honoured Sons',
    'Hospitallers',
    'Hounds of Demos',
    'Howling Griffons',
    'Illustrians',
    'Immortal Hearts',
    'Imperial Castellans',
    'Imperial Fists',
    'Imperial Harbingers',
    'Imperial Hawks',
    'Imperial Paladins',
    'Imperial Ravagers',
    'Imperial Stars',
    'Imperial Talons',
    'Imperius Reavers',
    'Inceptors',
    'Inculcators',
    'Interceptors',
    'Invaders',
    'Invictors',
    'Inviolators',
    'Iron Champions',
    'Iron Crusaders',
    'Iron Drakes',
    'Iron Fists',
    'Iron Hands',
    'Iron Hawks',
    'Iron Hearts',
    'Iron Hounds',
    'Iron Knights',
    'Iron Lords',
    'Iron Ravens',
    'Iron Scepters',
    'Iron Shield',
    'Iron Snakes',
    'Iron Talons',
    'Justicars',
    'Knights Cerulean',
    'Knights Excelsior',
    'Knights of Byzantium',
    'Knights of Dorn',
    'Knights of Eternity',
    'Knights of Gryphonne',
    'Knights of the Chalice',
    'Knights of the Crimson Order',
    'Knights of the Flame',
    'Knights of the Raven',
    'Knights of Thunder',
    'Knights Sanguine',
    'Knights Unyielding',
    'Lamenters',
    'Lances of Pteros',
    'Lectors of Ixis',
    'Legion of Night',
    'Legion of the Damned',
    'Libators',
    'Liberators',
    'Lion Warriors',
    'Lions Defiant',
    'Lions Sable',
    'Lionguard',
    'Lords of Wrath',
    'Malevolent',
    'Mantis Warriors',
    'Marauders',
    'Marines August',
    'Marines Errant',
    'Marines Errantor',
    'Marines Exemplar',
    'Marines Malevolent',
    'Marines Mordant',
    'Marines Vigilant',
    'Marines Vindicant',
    'Masters of Protelus',
    'Mentors',
    'Metamarines',
    'Minotaurs',
    'Mortifactors',
    'The Nameless',
    'Necropolis Hawks',
    'Nemesis',
    'Nemesors',
    'Night Hawks',
    'Night Swords',
    'Night Watch',
    'Nova Legion',
    'Nova Wings',
    'Novamarines',
    'Oblators',
    'Obsidian Glaives',
    'Obsidian Jaguars',
    'Omega Marines',
    'Pain Bringers',
    'Panthers',
    'Patriarchs of Ulixis',
    'Penitents',
    'Persecutors of Darkness',
    'Praetors of Orpheus',
    'Praetors of Ultramar',
    'Prophets of Mercury',
    'Purgators',
    'Purple Stars',
    'Rainbow Warriors',
    'Rampagers',
    'Raptors',
    'Raven Guard',
    "Raven's Watch",
    'Reclaimers',
    'Red Consuls',
    'Red Dragons',
    'Red Hunters',
    'Red Knights',
    'Red Legion',
    'Red Scimitars',
    'Red Scorpions',
    'Red Seraphs',
    'Red Talons',
    'Red Templars',
    'Red Wings',
    'Red Wolves',
    'Redeemed',
    'Redeemers',
    'Reparators',
    'Retractors',
    'Retributors',
    'Revilers',
    'Rhetors',
    'Rift Cobras',
    'Rift Stalkers',
    'Sable Brotherhood',
    'Sable Knights',
    'Sable Swords',
    'Salamanders',
    'Sanguine Host',
    'Scar Lords',
    'Scions of Iron',
    'Scions of Sanguinius',
    'Scythes of the Emperor',
    'Shadow Falcons',
    'Shadow Haunters',
    'Shadow Hawks',
    'Shadow Wolves',
    'Shadowhawks',
    'Silver Drakes',
    'Silver Eagles',
    'Silver Guard',
    'Silver Sabres',
    'Silver Skulls',
    'Silver Stars',
    'Silver Templars',
    'Skull Bearers',
    'Sky Sentinels',
    'Solar Hawks',
    'Sons of Antaeus',
    'Sons of Dorn',
    'Sons of Gorgax',
    'Sons of Guilliman',
    'Sons of Helios',
    'Sons of Jaghatai',
    'Sons of Medusa',
    'Sons of Orar',
    'Sons of Orpheus',
    'Sons of the Phoenix',
    'Sons of Sanguinius',
    'Sons of the Kraken',
    'Sons of the Raven',
    'Space Sharks',
    'Space Wolves',
    'Star Dragons',
    'Star Leopards',
    'Star Phantoms',
    'Star Scorpions',
    'Steel Confessors',
    'Stone Hearts',
    'Stone Gauntlets',
    'Storm Callers',
    'Storm Falcons',
    'Storm Giants',
    'Storm Hawks',
    'Storm Lords',
    'Storm Ravens',
    'Storm Reapers',
    'Storm Wardens',
    'Storm Warriors',
    'Storm Wings',
    'Stormwatchers',
    'Stormwalkers',
    'Subjugators',
    'Supplicators',
    'Swords of Praesium',
    'Swords of the Emperor',
    'Tarantulas',
    'Taurans',
    'Tempest Guard',
    'Tempestors',
    'Templars of Blood',
    'Templars of the Covenant',
    'Terror Tigers',
    'Tiger Claws',
    'Tigers Argent',
    'Tome Keepers',
    'Tormentors',
    'Tormented',
    'Tributors',
    'Ultramarines',
    'Umbral Knights',
    'Valedictors',
    'Valiant Blades',
    'Venerators of Osiron',
    'Venerators',
    'Victors',
    'Vindicators',
    'Viper Legion',
    'Void Tridents',
    'Vorpal Swords',
    'War Bearers',
    'Warhawks',
    'Warmongers',
    'Warrior Adepts',
    'Warriors Tempest',
    'Watchguards',
    'White Consuls',
    'White Minotaurs',
    'White Panthers',
    'White Scars',
    'White Templars',
    'Widowmakers',
    'Wolfspear',
    'Yellow Jackets',
]

males = [
    'Liam',
    'Noah',
    'Oliver',
    'Elijah',
    'William',
    'James',
    'Benjamin',
    'Lucas',
    'Henry',
    'Alexander',
    'Mason',
    'Michael',
    'Ethan',
    'Daniel',
    'Jacob',
    'Logan',
    'Jackson',
    'Levi',
    'Sebastian',
    'Mateo',
    'Jack',
    'Owen',
    'Theodore',
    'Aiden',
    'Samuel',
    'Joseph',
    'John',
    'David',
    'Wyatt',
    'Matthew',
    'Luke',
    'Asher',
    'Carter',
    'Julian',
    'Grayson',
    'Leo',
    'Jayden',
    'Gabriel',
    'Isaac',
    'Lincoln',
    'Anthony',
    'Hudson',
    'Dylan',
    'Ezra',
    'Thomas',
    'Charles',
    'Christopher',
    'Jaxon',
    'Maverick',
    'Josiah',
    'Isaiah',
    'Andrew',
    'Elias',
    'Joshua',
    'Nathan',
    'Caleb',
    'Ryan',
    'Adrian',
    'Miles',
    'Eli',
    'Nolan',
    'Christian',
    'Aaron',
    'Cameron',
    'Ezekiel',
    'Colton',
    'Luca',
    'Landon',
    'Hunter',
    'Jonathan',
    'Santiago',
    'Axel',
    'Easton',
    'Cooper',
    'Jeremiah',
    'Angel',
    'Roman',
    'Connor',
    'Jameson',
    'Robert',
    'Greyson',
    'Jordan',
    'Ian',
    'Carson',
    'Jaxson',
    'Leonardo',
    'Nicholas',
    'Dominic',
    'Austin',
    'Everett',
    'Brooks',
    'Xavier',
    'Kai',
    'Jose',
    'Parker',
    'Adam',
    'Jace',
    'Wesley',
    'Kayden',
    'Silas',
    'Bennett',
    'Declan',
    'Waylon',
    'Weston',
    'Evan',
    'Emmett',
    'Micah',
    'Ryder',
    'Beau',
    'Damian',
    'Brayden',
    'Gael',
    'Rowan',
    'Harrison',
    'Bryson',
    'Sawyer',
    'Amir',
    'Kingston',
    'Jason',
    'Giovanni',
    'Vincent',
    'Ayden',
    'Chase',
    'Myles',
    'Diego',
    'Nathaniel',
    'Legend',
    'Jonah',
    'River',
    'Tyler',
    'Cole',
    'Braxton',
    'George',
    'Milo',
    'Zachary',
    'Ashton',
    'Luis',
    'Jasper',
    'Kaiden',
    'Adriel',
    'Gavin',
    'Bentley',
    'Calvin',
    'Zion',
    'Juan',
    'Maxwell',
    'Max',
    'Ryker',
    'Carlos',
    'Emmanuel',
    'Jayce',
    'Lorenzo',
    'Ivan',
    'Jude',
    'August',
    'Kevin',
    'Malachi',
    'Elliott',
    'Rhett',
    'Archer',
    'Karter',
    'Arthur',
    'Luka',
    'Elliot',
    'Thiago',
    'Brandon',
    'Camden',
    'Justin',
    'Jesus',
    'Maddox',
    'King',
    'Theo',
    'Enzo',
    'Matteo',
    'Emiliano',
    'Dean',
    'Hayden',
    'Finn',
    'Brody',
    'Antonio',
    'Abel',
    'Alex',
    'Tristan',
    'Graham',
    'Zayden',
    'Judah',
    'Xander',
    'Miguel',
    'Atlas',
    'Messiah',
    'Barrett',
    'Tucker',
    'Timothy',
    'Alan',
    'Edward',
    'Leon',
    'Dawson',
    'Eric',
    'Ace',
    'Victor',
    'Abraham',
    'Nicolas',
    'Jesse',
    'Charlie',
    'Patrick',
    'Walker',
    'Joel',
    'Richard',
    'Beckett',
    'Blake',
    'Alejandro',
    'Avery',
    'Grant',
    'Peter',
    'Oscar',
    'Matias',
    'Amari',
    'Lukas',
    'Andres',
    'Arlo',
    'Colt',
    'Adonis',
    'Kyrie',
    'Steven',
    'Felix',
    'Preston',
    'Marcus',
    'Holden',
    'Emilio',
    'Remington',
    'Jeremy',
    'Kaleb',
    'Brantley',
    'Bryce',
    'Mark',
    'Knox',
    'Israel',
    'Phoenix',
    'Kobe',
    'Nash',
    'Griffin',
    'Caden',
    'Kenneth',
    'Kyler',
    'Hayes',
    'Jax',
    'Rafael',
    'Beckham',
    'Javier',
    'Maximus',
    'Simon',
    'Paul',
    'Omar',
    'Kaden',
    'Kash',
    'Lane',
    'Bryan',
    'Riley',
    'Zane',
    'Louis',
    'Aidan',
    'Paxton',
    'Maximiliano',
    'Karson',
    'Cash',
    'Cayden',
    'Emerson',
    'Tobias',
    'Ronan',
    'Brian',
    'Dallas',
    'Bradley',
    'Jorge',
    'Walter',
    'Josue',
    'Khalil',
    'Damien',
    'Jett',
    'Kairo',
    'Zander',
    'Andre',
    'Cohen',
    'Crew',
    'Hendrix',
    'Colin',
    'Chance',
    'Malakai',
    'Clayton',
    'Daxton',
    'Malcolm',
    'Lennox',
    'Martin',
    'Jaden',
    'Kayson',
    'Bodhi',
    'Francisco',
    'Cody',
    'Erick',
    'Kameron',
    'Atticus',
    'Dante',
    'Jensen',
    'Cruz',
    'Finley',
    'Brady',
    'Joaquin',
    'Anderson',
    'Gunner',
    'Muhammad',
    'Zayn',
    'Derek',
    'Raymond',
    'Kyle',
    'Angelo',
    'Reid',
    'Spencer',
    'Nico',
    'Jaylen',
    'Jake',
    'Prince',
    'Manuel',
    'Ali',
    'Gideon',
    'Stephen',
    'Ellis',
    'Orion',
    'Rylan',
    'Eduardo',
    'Mario',
    'Rory',
    'Cristian',
    'Odin',
    'Tanner',
    'Julius',
    'Callum',
    'Sean',
    'Kane',
    'Ricardo',
    'Travis',
    'Wade',
    'Warren',
    'Fernando',
    'Titus',
    'Leonel',
    'Edwin',
    'Cairo',
    'Corbin',
    'Dakota',
    'Ismael',
    'Colson',
    'Killian',
    'Major',
    'Tate',
    'Gianni',
    'Elian',
    'Remy',
    'Lawson',
    'Niko',
    'Nasir',
    'Kade',
    'Armani',
    'Ezequiel',
    'Marshall',
    'Hector',
    'Desmond',
    'Kason',
    'Garrett',
    'Jared',
    'Cyrus',
    'Russell',
    'Cesar',
    'Tyson',
    'Malik',
    'Donovan',
    'Jaxton',
    'Cade',
    'Romeo',
    'Nehemiah',
    'Sergio',
    'Iker',
    'Caiden',
    'Jay',
    'Pablo',
    'Devin',
    'Jeffrey',
    'Otto',
    'Kamari',
    'Ronin',
    'Johnny',
    'Clark',
    'Ari',
    'Marco',
    'Edgar',
    'Bowen',
    'Jaiden',
    'Grady',
    'Zayne',
    'Sullivan',
    'Jayceon',
    'Sterling',
    'Andy',
    'Conor',
    'Raiden',
    'Royal',
    'Royce',
    'Solomon',
    'Trevor',
    'Winston',
    'Emanuel',
    'Finnegan',
    'Pedro',
    'Luciano',
    'Harvey',
    'Franklin',
    'Noel',
    'Troy',
    'Princeton',
    'Johnathan',
    'Erik',
    'Fabian',
    'Oakley',
    'Rhys',
    'Porter',
    'Hugo',
    'Frank',
    'Damon',
    'Kendrick',
    'Mathias',
    'Milan',
    'Peyton',
    'Wilder',
    'Callan',
    'Gregory',
    'Seth',
    'Matthias',
    'Briggs',
    'Ibrahim',
    'Roberto',
    'Conner',
    'Quinn',
    'Kashton',
    'Sage',
    'Santino',
    'Kolton',
    'Alijah',
    'Dominick',
    'Zyaire',
    'Apollo',
    'Kylo',
    'Reed',
    'Philip',
    'Kian',
    'Shawn',
    'Kaison',
    'Leonidas',
    'Ayaan',
    'Lucca',
    'Memphis',
    'Ford',
    'Baylor',
    'Kyson',
    'Uriel',
    'Allen',
    'Collin',
    'Ruben',
    'Archie',
    'Dalton',
    'Esteban',
    'Adan',
    'Forrest',
    'Alonzo',
    'Isaias',
    'Leland',
    'Jase',
    'Dax',
    'Kasen',
    'Gage',
    'Kamden',
    'Marcos',
    'Jamison',
    'Francis',
    'Hank',
    'Alexis',
    'Tripp',
    'Frederick',
    'Jonas',
    'Stetson',
    'Cassius',
    'Izaiah',
    'Eden',
    'Maximilian',
    'Rocco',
    'Tatum',
    'Keegan',
    'Aziel',
    'Moses',
    'Bruce',
    'Lewis',
    'Braylen',
    'Omari',
]

females = [
    'Olivia',
    'Emma',
    'Ava',
    'Charlotte',
    'Sophia',
    'Amelia',
    'Isabella',
    'Mia',
    'Evelyn',
    'Harper',
    'Camila',
    'Gianna',
    'Abigail',
    'Luna',
    'Ella',
    'Elizabeth',
    'Sofia',
    'Emily',
    'Avery',
    'Mila',
    'Scarlett',
    'Eleanor',
    'Madison',
    'Layla',
    'Penelope',
    'Aria',
    'Chloe',
    'Grace',
    'Ellie',
    'Nora',
    'Hazel',
    'Zoey',
    'Riley',
    'Victoria',
    'Lily',
    'Aurora',
    'Violet',
    'Nova',
    'Hannah',
    'Emilia',
    'Zoe',
    'Stella',
    'Everly',
    'Isla',
    'Leah',
    'Lillian',
    'Addison',
    'Willow',
    'Lucy',
    'Paisley',
    'Natalie',
    'Naomi',
    'Eliana',
    'Brooklyn',
    'Elena',
    'Aubrey',
    'Claire',
    'Ivy',
    'Kinsley',
    'Audrey',
    'Maya',
    'Genesis',
    'Skylar',
    'Bella',
    'Aaliyah',
    'Madelyn',
    'Savannah',
    'Anna',
    'Delilah',
    'Serenity',
    'Caroline',
    'Kennedy',
    'Valentina',
    'Ruby',
    'Sophie',
    'Alice',
    'Gabriella',
    'Sadie',
    'Ariana',
    'Allison',
    'Hailey',
    'Autumn',
    'Nevaeh',
    'Natalia',
    'Quinn',
    'Josephine',
    'Sarah',
    'Cora',
    'Emery',
    'Samantha',
    'Piper',
    'Leilani',
    'Eva',
    'Everleigh',
    'Madeline',
    'Lydia',
    'Jade',
    'Peyton',
    'Brielle',
    'Adeline',
    'Vivian',
    'Rylee',
    'Clara',
    'Raelynn',
    'Melanie',
    'Melody',
    'Julia',
    'Athena',
    'Maria',
    'Liliana',
    'Hadley',
    'Arya',
    'Rose',
    'Reagan',
    'Eliza',
    'Adalynn',
    'Kaylee',
    'Lyla',
    'Mackenzie',
    'Alaia',
    'Isabelle',
    'Charlie',
    'Arianna',
    'Mary',
    'Remi',
    'Margaret',
    'Iris',
    'Parker',
    'Ximena',
    'Eden',
    'Ayla',
    'Kylie',
    'Elliana',
    'Josie',
    'Katherine',
    'Faith',
    'Alexandra',
    'Eloise',
    'Adalyn',
    'Amaya',
    'Jasmine',
    'Amara',
    'Daisy',
    'Reese',
    'Valerie',
    'Brianna',
    'Cecilia',
    'Andrea',
    'Summer',
    'Valeria',
    'Norah',
    'Ariella',
    'Esther',
    'Ashley',
    'Emerson',
    'Aubree',
    'Isabel',
    'Anastasia',
    'Ryleigh',
    'Khloe',
    'Taylor',
    'Londyn',
    'Lucia',
    'Emersyn',
    'Callie',
    'Sienna',
    'Blakely',
    'Kehlani',
    'Genevieve',
    'Alina',
    'Bailey',
    'Juniper',
    'Maeve',
    'Molly',
    'Harmony',
    'Georgia',
    'Magnolia',
    'Catalina',
    'Freya',
    'Juliette',
    'Sloane',
    'June',
    'Sara',
    'Ada',
    'Kimberly',
    'River',
    'Ember',
    'Juliana',
    'Aliyah',
    'Millie',
    'Brynlee',
    'Teagan',
    'Morgan',
    'Jordyn',
    'London',
    'Alaina',
    'Olive',
    'Rosalie',
    'Alyssa',
    'Ariel',
    'Finley',
    'Arabella',
    'Journee',
    'Hope',
    'Leila',
    'Alana',
    'Gemma',
    'Vanessa',
    'Gracie',
    'Noelle',
    'Marley',
    'Elise',
    'Presley',
    'Kamila',
    'Zara',
    'Amy',
    'Kayla',
    'Payton',
    'Blake',
    'Ruth',
    'Alani',
    'Annabelle',
    'Sage',
    'Aspen',
    'Laila',
    'Lila',
    'Rachel',
    'Trinity',
    'Daniela',
    'Alexa',
    'Lilly',
    'Lauren',
    'Elsie',
    'Margot',
    'Adelyn',
    'Zuri',
    'Brooke',
    'Sawyer',
    'Lilah',
    'Lola',
    'Selena',
    'Mya',
    'Sydney',
    'Diana',
    'Ana',
    'Vera',
    'Alayna',
    'Nyla',
    'Elaina',
    'Rebecca',
    'Angela',
    'Kali',
    'Alivia',
    'Raegan',
    'Rowan',
    'Phoebe',
    'Camilla',
    'Joanna',
    'Malia',
    'Vivienne',
    'Dakota',
    'Brooklynn',
    'Evangeline',
    'Camille',
    'Jane',
    'Nicole',
    'Catherine',
    'Jocelyn',
    'Julianna',
    'Lena',
    'Lucille',
    'Mckenna',
    'Paige',
    'Adelaide',
    'Charlee',
    'Mariana',
    'Myla',
    'Mckenzie',
    'Tessa',
    'Miriam',
    'Oakley',
    'Kailani',
    'Alayah',
    'Amira',
    'Adaline',
    'Phoenix',
    'Milani',
    'Annie',
    'Lia',
    'Angelina',
    'Harley',
    'Cali',
    'Maggie',
    'Hayden',
    'Leia',
    'Fiona',
    'Briella',
    'Journey',
    'Lennon',
    'Saylor',
    'Jayla',
    'Kaia',
    'Thea',
    'Adriana',
    'Mariah',
    'Juliet',
    'Oaklynn',
    'Kiara',
    'Alexis',
    'Haven',
    'Aniyah',
    'Delaney',
    'Gracelynn',
    'Kendall',
    'Winter',
    'Lilith',
    'Logan',
    'Amiyah',
    'Evie',
    'Alexandria',
    'Gracelyn',
    'Gabriela',
    'Sutton',
    'Harlow',
    'Madilyn',
    'Makayla',
    'Evelynn',
    'Gia',
    'Nina',
    'Amina',
    'Giselle',
    'Brynn',
    'Blair',
    'Amari',
    'Octavia',
    'Michelle',
    'Talia',
    'Demi',
    'Alaya',
    'Kaylani',
    'Izabella',
    'Fatima',
    'Tatum',
    'Makenzie',
    'Lilliana',
    'Arielle',
    'Palmer',
    'Melissa',
    'Willa',
    'Samara',
    'Destiny',
    'Dahlia',
    'Celeste',
    'Ainsley',
    'Rylie',
    'Reign',
    'Laura',
    'Adelynn',
    'Gabrielle',
    'Remington',
    'Wren',
    'Brinley',
    'Amora',
    'Lainey',
    'Collins',
    'Lexi',
    'Aitana',
    'Alessandra',
    'Kenzie',
    'Raelyn',
    'Elle',
    'Everlee',
    'Haisley',
    'Hallie',
    'Wynter',
    'Daleyza',
    'Gwendolyn',
    'Paislee',
    'Ariyah',
    'Veronica',
    'Heidi',
    'Anaya',
    'Cataleya',
    'Kira',
    'Avianna',
    'Felicity',
    'Aylin',
    'Miracle',
    'Sabrina',
    'Lana',
    'Ophelia',
    'Elianna',
    'Royalty',
    'Madeleine',
    'Esmeralda',
    'Joy',
    'Kalani',
    'Esme',
    'Jessica',
    'Leighton',
    'Ariah',
    'Makenna',
    'Nylah',
    'Viviana',
    'Camryn',
    'Cassidy',
    'Dream',
    'Luciana',
    'Maisie',
    'Stevie',
    'Kate',
    'Lyric',
    'Daniella',
    'Alicia',
    'Daphne',
    'Frances',
    'Charli',
    'Raven',
    'Paris',
    'Nayeli',
    'Serena',
    'Heaven',
    'Bianca',
    'Helen',
    'Hattie',
    'Averie',
    'Mabel',
    'Selah',
    'Allie',
    'Marlee',
    'Kinley',
    'Regina',
    'Carmen',
    'Jennifer',
    'Jordan',
    'Alison',
    'Stephanie',
    'Maren',
    'Kayleigh',
    'Angel',
    'Annalise',
    'Jacqueline',
    'Braelynn',
    'Emory',
    'Rosemary',
    'Scarlet',
    'Amanda',
    'Danielle',
    'Emelia',
    'Ryan',
    'Carolina',
    'Astrid',
    'Kensley',
    'Shiloh',
    'Maci',
    'Francesca',
    'Rory',
    'Celine',
    'Kamryn',
    'Zariah',
    'Liana',
    'Poppy',
    'Maliyah',
    'Keira',
    'Skyler',
    'Noa',
    'Skye',
    'Nadia',
    'Addilyn',
    'Rosie',
    'Eve',
    'Sarai',
    'Edith',
    'Jolene',
    'Maddison',
    'Meadow',
    'Charleigh',
    'Matilda',
    'Elliott',
    'Madelynn',
    'Holly',
    'Leona',
    'Azalea',
    'Katie',
    'Mira',
    'Ari',
    'Kaitlyn',
    'Danna',
    'Cameron',
    'Kyla',
    'Bristol',
    'Kora',
    'Armani',
    'Nia',
    'Malani',
    'Dylan',
    'Remy',
    'Maia',
    'Dior',
    'Legacy',
]

humans = sorted(list(set(males + females)))

def generate_chapter():
    return random.choice(chapters)

def generate_human():
    return random.choice(humans)
