# Generated by Django 3.2.3 on 2021-05-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('site_supported', models.CharField(choices=[('Adidas', 'Adidas'), ('Shopify', 'Shopify'), ('Supreme', 'Supreme'), ('Footsites', 'Footsites'), ('YeezySupply', 'YeezySupply'), ('Mesh', 'Mesh'), ('AIO', 'AIO')], max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_approved', models.BooleanField(null=True)),
            ],
        ),
    ]
