# Generated by Django 3.2.3 on 2021-05-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
