# Generated by Django 3.2.3 on 2021-05-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_alter_bot_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='bot',
            name='site_supported',
            field=models.CharField(max_length=100),
        ),
    ]
